apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
      - name: discord-bot
        image: ghcr.io/order-of-devs/discord-bot:latest
        imagePullPolicy: Always
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-secret
              key: token
      imagePullSecrets:
        - name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  name: discord-bot-service
spec:
  selector:
    app: discord-bot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
